name: upload-to-oss
on: workflow_dispatch
jobs:
  upload-to-oss:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/checkout@master
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_KEY_SECRET  }}
      - run: ossutil cp -rf ./u2o-test/ oss://capital-lb --exclude index.html
      - run: ossutil cp -rf ./u2o-test/ oss://capital-lb --include index.html
